postgresql: &postgresql
  adapter: postgresql
  host: 10.0.2.2
  user: retos
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: retos_cmx_development

test:
  <<: *postgresql
  database: retos_cmx_test

production:
  <<: *postgresql
  database: retos_cmx
