####################################
########### DEFAULT KEYS ###########
####################################

POSTGRES_USER: retos
POSTGRES_HOST: localhost
POSTGRES_DB: retos_cmx

APP_NAME:
APP_URL:
LOGO: logocmx@2x.png

# Github
GITHUB_KEY:
GITHUB_SECRET:

# LinkedIn
LINKEDIN_KEY:
LINKEDIN_SECRET:

# Facebook
FACEBOOK_KEY:
FACEBOOK_SECRET:

# Twitter
TWITTER_KEY:
TWITTER_SECRET:
TWITTER_ACCESS_KEY:
TWITTER_ACCESS_SECRET:

# Ckan (Data MX)
CKAN_API_KEY:
CKAN_API_BASE:

# Mailing
SMTP_CONFIG_USERNAME:
SMTP_CONFIG_PASSWORD:
SMTP_CONFIG_DOMAIN:
SMTP_CONFIG_ADDRESS:
ACTION_MAILER_HOST:
MAILER_DEFAULT_FROM: 'Codeando México <equipo@codeandomexico.org>'

# Error reporting
AIRBRAKE_KEY:

# Storage bucket
AMAZON_ACCESS_KEY:
AMAZON_SECRET_KEY:
S3_BUCKET:

# Performance metrics
NEW_RELIC_KEY:

# Secret key for signed cookies
SECRET_TOKEN:
# Set to a 128 characters hexadecimal string
DEVISE_KEY:

GOOGLE_ANALYTICS:

# Host assets elsewhere
ASSET_HOST: # Starts with // e.g.: //d121.cloudfront.net
