postgresql: &postgresql
  adapter: postgresql
  host: localhost
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: retos_cmx_development
  username: postgres
  password: postgres
  template: template0

test:
  <<: *postgresql
  database: retos_cmx_test
  username: postgres
  password: postgres
  template: template0

production:
  <<: *postgresql
  database: retos_cmx_production
  username: postgres
  password: postgres
  template: template0
