postgresql: &postgresql
  adapter: postgresql
  host: <%= ENV['POSTGRES_HOST'] %>
  user: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  min_messages: ERROR
  pool: 5
  timeout: 5000

development:
  <<: *postgresql
  database: <%= ENV['POSTGRES_DB'] %>_development

test:
  <<: *postgresql
  database: <%= ENV['POSTGRES_DB'] %>_test

production:
  <<: *postgresql
  database: <%= ENV['POSTGRES_DB'] %>
